on:
  push:
    branches:
      - master  # إضافة مسافة بعد "-" لتصحيح اسم الفرع

jobs:
  build:
    runs-on: ubuntu-latest  # تصحيح إلى ubuntu-latest بدون underscore

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Login to Docker Hub"
        run: docker login --username samarkhaled427 --password Mull07689

      - name: "Build Docker image"
        run: docker build -t samarkhaled427/my-image . 