on:
   push:
      branches:
          -master

jobs:
   build:
      runs-on: ubuntu_latest

    steps:
       -uses: actions/checkout@v3

       -name: "login to docker hub"
        run:docker login --username samar.khaled22164@ci.menofia.edu.eg --password Mull07689

        -name: "bulding docker image"
         run: docker build -t samar.khaled22164@ci.menofia.edu.eg /my image
